name: Playwright Tests Arati
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]


jobs:
  PlaywrightTest:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    environment: ARTENV

    env:
      BASE_URL: ${{ vars.BASE_URL   }}
      EMAIL: ${{ vars.EMAIL }}
      PASSWORD: ${{ vars.PASSWORD }}
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci

    - name: create .env file
      run: |
        echo "BASE_URL=${{ $BASE_URL }}" >> .env
        echo "EMAIL=${{ $EMAIL }}" >> .env
        echo "PASSWORD=${{ $PASSWORD }}" >> .env
        

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test:smoke
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
      
        name: playwright-report
        path: playwright-report/
        retention-days: 30
